services:
  app:
    # On utilise une variable d'environnement ou le tag direct
    image: ${IMAGE_NAME:-ghcr.io/ton_user/ton_repo:latest}
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./volumes:/app/volumes
    env_file:
      - .env
    restart: unless-stopped
